/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_wzq_compressimg_NativeUtil */
#include "com_wzq_compressimg_NativeUtil.h"
#include "bitherlibjni.h"
//#ifndef _Included_com_wzq_compressimg_NativeUtil
//#define _Included_com_wzq_compressimg_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzq_compressimg_NativeUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzq_compressimg_NativeUtil_compressBitmap
        (JNIEnv *env, jclass thiz, jobject bitmapcolor, int w, int h, int quality,
   jbyteArray fileNameStr, jboolean optimize)
   {
        return Java_net_bither_util_NativeUtil_compressBitmap(env,
		 thiz,  bitmapcolor,  w,  h,  quality,
		 fileNameStr,  optimize);
   }

#ifdef __cplusplus
}
#endif
//#endif
