/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzq_compressimg_NativeUtil */

#ifndef _Included_com_wzq_compressimg_NativeUtil
#define _Included_com_wzq_compressimg_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzq_compressimg_NativeUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzq_compressimg_NativeUtil_compressBitmap
  (JNIEnv *env, jobject thiz, jobject bitmapcolor, int w, int h, int quality,
   jbyteArray fileNameStr, jboolean optimize);

#ifdef __cplusplus
}
#endif
#endif
